### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by volodymyrdovhan** [28Smiles/moodle-qtdeferredfeedback#1]
Hello,
I have an error on the privacy registry:

![image](https://github.com/user-attachments/assets/5a2ff7db-7ee6-471e-b9bb-cf799e4b37f4)

**Comment by 28Smiles** [comment]
Thank you for your report, apparently i missed renaming a class. I will fix that.

**Comment by 28Smiles** [comment]
Fixed
